baseURL = "http://infracode.ru"
languageCode = "en-us"
#title = "Хуёчим-тамагочем"
theme = "osprey"

[Params]
  tagline = "$ oc new-project your_name"
  author = "Toma Nistor"
  description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
  logoBig = "/images/infracode-logo.png"
  logoSmall = "/images/infracode-logo.png"
  favicon = "favicon.ico"

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

[[menu.main]]
  name = "Компания"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Услуги"
  url  = "/#services"
  weight = 2
[[menu.main]]
  name = "Продукты"
  url  = "/#products"
  weight = 3
[[menu.main]]
  name = "Контакты"
  url  = "/#contact"
  weight = 4
